// Police spending next to reported crime — two public series, one page.
//
// Generated by etl/parse_police_crime.py. Spending is the Police department's
// appropriations in the Town's own adopted budgets; crime is New York State
// DCJS's Index Crime count for Riverhead Town PD, the series behind the State's
// public Index Crimes dashboard.
//
// ON PUTTING THEM TOGETHER. Two measures on different scales must never share a
// y-axis — that is the chart that makes any two lines look related. They are
// shown here as their own charts, and compared by indexing both to a common
// base year, which is the only honest way to answer "which grew faster".
//
// The base is 2021, not 2020. 2020 is a pandemic year: Riverhead recorded 503
// index crimes, far below every year around it, so anchoring to it would
// manufacture a crime surge out of a return to normal. 2020 is still plotted —
// it is just not the denominator.

import data from '../public/data/police-crime.json'

export type CrimeYear = {
  year: number
  monthsReported: number | null
  total: number | null
  violent: number | null
  property: number | null
  burglary: number | null
  larceny: number | null
  motorVehicleTheft: number | null
  robbery: number | null
  aggravatedAssault: number | null
  murder: number | null
  forcibleRape: number | null
}

export type JoinedYear = {
  year: number
  appropriation: number
  totalIndexCrimes: number | null
  violent: number | null
  property: number | null
  monthsReported: number | null
  dollarsPerReportedIndexCrime: number | null
}

export type PeerAgency = {
  agency: string
  year: number
  total: number | null
  violent: number | null
  property: number | null
  monthsReported: number | null
  population: number | null
  per10k: number | null
  isRiverhead: boolean
}

export const agency = data.agency as string
export const crime = data.crime as CrimeYear[]
export const spending = data.spending as { year: number; appropriation: number }[]
export const joined = data.joined as JoinedYear[]
export const peersLatest = data.peersLatest as PeerAgency[]
/** Peer bars are rates only when a Census population was available at build time. */
export const peersHavePopulation = (data as { peersHavePopulation?: boolean }).peersHavePopulation === true
export const method = data.method as string
export const sources = data.sources as { title: string; url: string; note?: string; dashboard?: string }[]
export const dataLimits = data.limits as string[]

/** Pandemic year — plotted, never used as a baseline. */
export const BASE_YEAR = 2021

export const latest = joined.length ? joined[joined.length - 1] : null
export const base = joined.find((j) => j.year === BASE_YEAR) ?? joined[0] ?? null

/** Both series rebased to 100 so one axis can carry them honestly. */
export const indexed = joined.map((j) => ({
  year: j.year,
  spending: base ? (j.appropriation / base.appropriation) * 100 : null,
  crime: base?.totalIndexCrimes && j.totalIndexCrimes
    ? (j.totalIndexCrimes / base.totalIndexCrimes) * 100
    : null,
}))

function pctChange(from: number | null | undefined, to: number | null | undefined) {
  if (!from || !to) return null
  return ((to - from) / from) * 100
}

export const sinceBase = {
  baseYear: BASE_YEAR,
  latestYear: latest?.year ?? null,
  spendingPct: pctChange(base?.appropriation, latest?.appropriation),
  crimePct: pctChange(base?.totalIndexCrimes, latest?.totalIndexCrimes),
  violentPct: pctChange(base?.violent, latest?.violent),
  propertyPct: pctChange(base?.property, latest?.property),
}

/** The 2026 adopted figure, which is past the end of the State's crime series. */
export const adoptedBeyondCrimeData = (() => {
  const beyond = spending.filter((s) => !joined.some((j) => j.year === s.year))
  return beyond.length ? beyond[beyond.length - 1] : null
})()

/**
 * What the composition says, which is the part a single total hides.
 *
 * Riverhead's index crime is overwhelmingly property crime, and almost all of
 * that is larceny. Violent crime is a small and roughly flat number. A total
 * that moves is usually larceny moving.
 */
export const composition = (() => {
  const l = crime[crime.length - 1]
  if (!l?.total) return null
  return {
    year: l.year,
    total: l.total,
    larceny: l.larceny,
    larcenyShare: l.larceny ? l.larceny / l.total : null,
    violent: l.violent,
    violentShare: l.violent ? l.violent / l.total : null,
    property: l.property,
  }
})()

/**
 * Years the State published as a complete annual count.
 *
 * months_reported is only populated from 2002 on. Before that the column is
 * null for every agency — which means "not recorded", not "partial year", and
 * filtering those rows out silently dropped 1990-2001 and with them the fact
 * that today's count is about half the level of 2000.
 */
export const completeYears = crime.filter((c) => c.total != null && (c.monthsReported == null || c.monthsReported === 12))

export const longRun = (() => {
  const withTotals = completeYears.filter((c) => c.total != null)
  if (!withTotals.length || !latest?.totalIndexCrimes) return null
  const peak = withTotals.reduce((a, b) => ((b.total ?? 0) > (a.total ?? 0) ? b : a))
  const firstYear = withTotals[0]
  return {
    firstYear: firstYear.year,
    peakYear: peak.year,
    peakTotal: peak.total as number,
    latestYear: latest.year,
    latestTotal: latest.totalIndexCrimes,
    shareOfPeak: latest.totalIndexCrimes / (peak.total as number),
    monthsReportedFrom: 2002,
  }
})()

/**
 * Peers with a full twelve months reported — the only fair comparison.
 *
 * Sorted by whatever is actually plotted. The ETL orders by raw total, which
 * left the bars non-monotonic once the chart switched to rates: Southampton has
 * the larger count and the smaller rate, so it sat above Southold with a shorter
 * bar. A bar chart whose order disagrees with its lengths is just wrong.
 */
export const peersComparable = peersLatest
  .filter((p) => p.monthsReported === 12)
  .slice()
  .sort((a, b) =>
    peersHavePopulation
      ? (b.per10k ?? 0) - (a.per10k ?? 0)
      : (b.total ?? 0) - (a.total ?? 0),
  )
export const peersPartial = peersLatest.filter((p) => p.monthsReported !== 12)

/** Riverhead's own population, from the peer fetch — used for per-resident cost. */
export const riverheadPopulation =
  peersLatest.find((p) => p.isRiverhead)?.population ?? null

export const perResident = (() => {
  if (!riverheadPopulation) return null
  const adopted = spending[spending.length - 1]
  return {
    year: adopted.year,
    appropriation: adopted.appropriation,
    population: riverheadPopulation,
    dollarsPerResident: adopted.appropriation / riverheadPopulation,
  }
})()

/**
 * How Riverhead's reported rate sits against the East End towns that reported a
 * full year. Rates, not counts — Southampton has nearly twice Riverhead's
 * population and reports half the index crime, which a bar chart of raw totals
 * hides completely.
 */
export const rateComparison = (() => {
  const me = peersComparable.find((p) => p.isRiverhead)
  const others = peersComparable.filter((p) => !p.isRiverhead && p.per10k)
  if (!me?.per10k || !others.length) return null
  const nearest = others.reduce((a, b) => ((b.per10k ?? 0) > (a.per10k ?? 0) ? b : a))
  const mean = others.reduce((sum, p) => sum + (p.per10k ?? 0), 0) / others.length
  return {
    riverheadPer10k: me.per10k,
    nearestAgency: nearest.agency,
    nearestPer10k: nearest.per10k as number,
    multipleOfNearest: me.per10k / (nearest.per10k as number),
    multipleOfPeerMean: me.per10k / mean,
    peerMean: mean,
    year: me.year,
  }
})()

/**
 * The caveat that has to travel with any per-capita crime rate for a town with
 * a regional shopping district. It is a methodological point, not an excuse.
 */
export const rateCaveat =
  'A per-capita crime rate divides by the people who LIVE somewhere. Riverhead’s index crime is about nine-tenths larceny, and larceny is recorded where the retail is, by and against people who may live anywhere on the East End or beyond. A town that hosts the region’s shopping will record more theft per resident than its neighbours whatever its policing, so this rate measures what the department writes down, not how safe a resident is at home.'

/**
 * Why these four towns and no others.
 *
 * Riverhead runs its own police department because it declined to join the
 * county one. After New York passed the legislation creating Suffolk's county-
 * executive government in 1958, a referendum put the question of a county
 * police force to the towns. The five western towns — Babylon, Huntington,
 * Islip, Smithtown and Brookhaven — voted to join; the five eastern ones —
 * Riverhead, Southold, Shelter Island, East Hampton and Southampton — kept
 * their own forces. The Suffolk County Police Department began operating on
 * January 1, 1960, and the split has held ever since.
 *
 * This is not background colour. It is what makes the peer comparison on this
 * page the COMPLETE set rather than a selection: the five East End towns are
 * the only towns in Suffolk County that have a town police department at all,
 * so they are the only ones with a town police appropriation to compare. A
 * Brookhaven or Islip resident pays for policing through a county police
 * district tax, not through a town budget line, and there is no equivalent
 * figure to put beside Riverhead's.
 */
export type PoliceDistrict = {
  countyPopulation: number
  eastEndPopulation: number
  countyPolicedPopulation: number
  countyPolicedShare: number
  townsCounted: string[]
}

/** Computed from Census populations, not asserted as a rough fraction. */
export const policeDistrict = (data as { policeDistrict?: PoliceDistrict | null }).policeDistrict ?? null

export const whyOwnDepartment = {
  enablingLegislation: 1958,
  countyDepartmentBegan: 'January 1, 1960',
  joinedCountyDistrict: ['Babylon', 'Huntington', 'Islip', 'Smithtown', 'Brookhaven'],
  keptOwnDepartment: ['Riverhead', 'Southold', 'Shelter Island', 'East Hampton', 'Southampton'],
  get whyItMatters() {
    const share = policeDistrict
      ? `${(policeDistrict.countyPolicedShare * 100).toFixed(1)}% of Suffolk’s population`
      : 'most of Suffolk’s population'
    return (
      'Police is the largest single department in Riverhead’s General Fund. That it sits in the town budget at all — ' +
      `rather than in a county police district tax, as it does for ${share} — is a structural decision taken around 1960 ` +
      'and never revisited. It is also why this page compares Riverhead only with the other four East End towns: they ' +
      'are not the nearest neighbours, they are the entire set of Suffolk towns that still have a town police line to compare.'
    )
  },
  sourcing:
    'Secondary accounts differ on whether the referendum itself fell in 1958 or 1959; they agree on the 1958 enabling legislation and on the department beginning operations January 1, 1960, so this page states those and not a contested referendum date. The record that would settle it is the Suffolk County Charter’s police-district provisions and the referendum return itself, neither of which is published in a machine-readable form.',
  sources: [
    {
      title: 'Suffolk County Police Department — history of the county police district referendum',
      url: 'https://en.wikipedia.org/wiki/Suffolk_County_Police_Department',
      kind: 'secondary' as const,
    },
    {
      title: 'RiverheadLOCAL, “Suffolk Closeup: County cops meddling in local politics is a decades-old pattern” (10/24/2015)',
      url: 'https://riverheadlocal.com/2015/10/24/suffolk-closeup-county-cops-meddling-in-local-politics-is-a-decades-old-pattern/',
      kind: 'secondary' as const,
    },
    {
      title: 'Suffolk County Charter — police district provisions (the primary record, not published machine-readably)',
      url: 'https://suffolkcountyny.gov/',
      kind: 'primary-unpublished' as const,
    },
  ],
}

export const workSession = {
  title: 'Town Board Work Session, September 17, 2026 — agenda item 1, monthly report for the Police Department',
  url: 'https://riverheadny.portal.civicclerk.com/event/6497/files/agenda/12360',
  note:
    'The Police Department reports to the Board monthly and the Justice Court, Code Enforcement and Town Clerk report alongside it. Those monthly figures are published as scanned images inside the agenda packet, with no text layer, so they cannot be read by software — including the Town’s own. This page therefore uses the State’s annual series, which is machine-readable and comparable across departments.',
}

export const caution =
  'Neither line explains the other, and the page does not suggest it does. Spending buys staffing, contractual raises and equipment; reported crime moves with what happens and with what gets reported. A department that prevents a crime records fewer of them, not more — so a falling count is not a failing department and a rising one is not a failing budget. What the pair does answer is narrower and still worth asking: what has the Town been paying, what has it been recording, and how does that sit next to the neighbours who publish the same two numbers.'
